import {
  Chrome,
  Shield,
  Code,
  FileCode,
  Github,
  Pi,
  Box,
  Archive,
  FileText,
  Settings,
  SearchIcon,
  Play,
  Music,
  MessageSquare,
  Slack,
  Video,
  Layout,
  TerminalIcon,
  MonitorSmartphone,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

/**
 * Application interface defining the structure of application data
 */
export interface Application {
  id: string
  name: string
  description: string
  command: string
  category: string
  recommended: boolean
  icon: LucideIcon
}

/**
 * Operating system type
 */
export type OperatingSystem = "windows" | "macos" | "linux"

/**
 * Applications data organized by operating system
 */
export const applications: Record<OperatingSystem, Application[]> = {
  windows: [
    {
      id: "chrome",
      name: "Google Chrome",
      description: "Fast, secure web browser",
      command: "choco install googlechrome",
      category: "Browsers",
      recommended: true,
      icon: Chrome,
    },
    {
      id: "firefox",
      name: "Firefox",
      description: "Privacy-focused browser",
      command: "choco install firefox",
      category: "Browsers",
      recommended: false,
      icon: Chrome,
    },
    {
      id: "brave",
      name: "Brave",
      description: "Privacy-first browser with ad blocking",
      command: "choco install brave",
      category: "Browsers",
      recommended: false,
      icon: Shield,
    },

    {
      id: "vscode",
      name: "Visual Studio Code",
      description: "Powerful code editor",
      command: "choco install vscode",
      category: "Development",
      recommended: true,
      icon: Code,
    },
    {
      id: "node",
      name: "Node.js",
      description: "JavaScript runtime environment",
      command: "choco install nodejs",
      category: "Development",
      recommended: true,
      icon: FileCode,
    },
    {
      id: "git",
      name: "Git",
      description: "Distributed version control",
      command: "choco install git",
      category: "Development",
      recommended: true,
      icon: Github,
    },
    {
      id: "python",
      name: "Python",
      description: "Programming language",
      command: "choco install python",
      category: "Development",
      recommended: false,
      icon: Pi,
    },
    {
      id: "docker",
      name: "Docker Desktop",
      description: "Container platform",
      command: "choco install docker-desktop",
      category: "Development",
      recommended: false,
      icon: Box,
    },

    {
      id: "7zip",
      name: "7-Zip",
      description: "File compression utility",
      command: "choco install 7zip",
      category: "Utilities",
      recommended: true,
      icon: Archive,
    },
    {
      id: "notepadpp",
      name: "Notepad++",
      description: "Advanced text editor",
      command: "choco install notepadplusplus",
      category: "Utilities",
      recommended: true,
      icon: FileText,
    },
    {
      id: "powertoys",
      name: "PowerToys",
      description: "Windows productivity tools",
      command: "choco install powertoys",
      category: "Utilities",
      recommended: false,
      icon: Settings,
    },
    {
      id: "everything",
      name: "Everything",
      description: "Fast file search utility",
      command: "choco install everything",
      category: "Utilities",
      recommended: false,
      icon: SearchIcon,
    },

    {
      id: "vlc",
      name: "VLC",
      description: "Versatile media player",
      command: "choco install vlc",
      category: "Media",
      recommended: true,
      icon: Play,
    },
    {
      id: "spotify",
      name: "Spotify",
      description: "Music streaming service",
      command: "choco install spotify",
      category: "Media",
      recommended: false,
      icon: Music,
    },

    {
      id: "discord",
      name: "Discord",
      description: "Voice and text chat platform",
      command: "choco install discord",
      category: "Communication",
      recommended: false,
      icon: MessageSquare,
    },
    {
      id: "slack",
      name: "Slack",
      description: "Business communication platform",
      command: "choco install slack",
      category: "Communication",
      recommended: false,
      icon: Slack,
    },
    {
      id: "zoom",
      name: "Zoom",
      description: "Video conferencing tool",
      command: "choco install zoom",
      category: "Communication",
      recommended: false,
      icon: Video,
    },
  ],
  macos: [
    {
      id: "chrome",
      name: "Google Chrome",
      description: "Fast, secure web browser",
      command: "brew install --cask google-chrome",
      category: "Browsers",
      recommended: true,
      icon: Chrome,
    },
    {
      id: "firefox",
      name: "Firefox",
      description: "Privacy-focused browser",
      command: "brew install --cask firefox",
      category: "Browsers",
      recommended: false,
      icon: Chrome,
    },
    {
      id: "brave",
      name: "Brave",
      description: "Privacy-first browser with ad blocking",
      command: "brew install --cask brave-browser",
      category: "Browsers",
      recommended: false,
      icon: Shield,
    },

    {
      id: "vscode",
      name: "Visual Studio Code",
      description: "Powerful code editor",
      command: "brew install --cask visual-studio-code",
      category: "Development",
      recommended: true,
      icon: Code,
    },
    {
      id: "node",
      name: "Node.js",
      description: "JavaScript runtime environment",
      command: "brew install node",
      category: "Development",
      recommended: true,
      icon: FileCode,
    },
    {
      id: "git",
      name: "Git",
      description: "Distributed version control",
      command: "brew install git",
      category: "Development",
      recommended: true,
      icon: Github,
    },
    {
      id: "python",
      name: "Python",
      description: "Programming language",
      command: "brew install python",
      category: "Development",
      recommended: false,
      icon: Pi,
    },
    {
      id: "docker",
      name: "Docker Desktop",
      description: "Container platform",
      command: "brew install --cask docker",
      category: "Development",
      recommended: false,
      icon: Box,
    },

    {
      id: "rectangle",
      name: "Rectangle",
      description: "Window management tool",
      command: "brew install --cask rectangle",
      category: "Utilities",
      recommended: true,
      icon: Layout,
    },
    {
      id: "iterm2",
      name: "iTerm2",
      description: "Enhanced terminal emulator",
      command: "brew install --cask iterm2",
      category: "Utilities",
      recommended: true,
      icon: TerminalIcon,
    },
    {
      id: "alfred",
      name: "Alfred",
      description: "Productivity application",
      command: "brew install --cask alfred",
      category: "Utilities",
      recommended: true,
      icon: SearchIcon,
    },
    {
      id: "bartender",
      name: "Bartender",
      description: "Menu bar organization tool",
      command: "brew install --cask bartender",
      category: "Utilities",
      recommended: false,
      icon: Settings,
    },

    {
      id: "vlc",
      name: "VLC",
      description: "Versatile media player",
      command: "brew install --cask vlc",
      category: "Media",
      recommended: true,
      icon: Play,
    },
    {
      id: "spotify",
      name: "Spotify",
      description: "Music streaming service",
      command: "brew install --cask spotify",
      category: "Media",
      recommended: false,
      icon: Music,
    },

    {
      id: "discord",
      name: "Discord",
      description: "Voice and text chat platform",
      command: "brew install --cask discord",
      category: "Communication",
      recommended: false,
      icon: MessageSquare,
    },
    {
      id: "slack",
      name: "Slack",
      description: "Business communication platform",
      command: "brew install --cask slack",
      category: "Communication",
      recommended: false,
      icon: Slack,
    },
    {
      id: "zoom",
      name: "Zoom",
      description: "Video conferencing tool",
      command: "brew install --cask zoom",
      category: "Communication",
      recommended: false,
      icon: Video,
    },
  ],
  linux: [
    {
      id: "chrome",
      name: "Google Chrome",
      description: "Fast, secure web browser",
      command: "sudo apt install google-chrome-stable",
      category: "Browsers",
      recommended: true,
      icon: Chrome,
    },
    {
      id: "firefox",
      name: "Firefox",
      description: "Privacy-focused browser",
      command: "sudo apt install firefox",
      category: "Browsers",
      recommended: false,
      icon: Chrome,
    },
    {
      id: "brave",
      name: "Brave",
      description: "Privacy-first browser with ad blocking",
      command: "sudo apt install brave-browser",
      category: "Browsers",
      recommended: false,
      icon: Shield,
    },

    {
      id: "vscode",
      name: "Visual Studio Code",
      description: "Powerful code editor",
      command: "sudo apt install code",
      category: "Development",
      recommended: true,
      icon: Code,
    },
    {
      id: "node",
      name: "Node.js",
      description: "JavaScript runtime environment",
      command: "sudo apt install nodejs",
      category: "Development",
      recommended: true,
      icon: FileCode,
    },
    {
      id: "git",
      name: "Git",
      description: "Distributed version control",
      command: "sudo apt install git",
      category: "Development",
      recommended: true,
      icon: Github,
    },
    {
      id: "python",
      name: "Python",
      description: "Programming language",
      command: "sudo apt install python3",
      category: "Development",
      recommended: false,
      icon: Pi,
    },
    {
      id: "docker",
      name: "Docker",
      description: "Container platform",
      command: "sudo apt install docker.io",
      category: "Development",
      recommended: false,
      icon: Box,
    },

    {
      id: "vim",
      name: "Vim",
      description: "Advanced text editor",
      command: "sudo apt install vim",
      category: "Utilities",
      recommended: true,
      icon: FileText,
    },
    {
      id: "htop",
      name: "htop",
      description: "Interactive process viewer",
      command: "sudo apt install htop",
      category: "Utilities",
      recommended: true,
      icon: MonitorSmartphone,
    },
    {
      id: "tmux",
      name: "tmux",
      description: "Terminal multiplexer",
      command: "sudo apt install tmux",
      category: "Utilities",
      recommended: false,
      icon: TerminalIcon,
    },
    {
      id: "gnome-tweaks",
      name: "GNOME Tweaks",
      description: "Desktop customization tool",
      command: "sudo apt install gnome-tweaks",
      category: "Utilities",
      recommended: false,
      icon: Settings,
    },

    {
      id: "vlc",
      name: "VLC",
      description: "Versatile media player",
      command: "sudo apt install vlc",
      category: "Media",
      recommended: true,
      icon: Play,
    },
    {
      id: "spotify",
      name: "Spotify",
      description: "Music streaming service",
      command: "sudo snap install spotify",
      category: "Media",
      recommended: false,
      icon: Music,
    },

    {
      id: "discord",
      name: "Discord",
      description: "Voice and text chat platform",
      command: "sudo snap install discord",
      category: "Communication",
      recommended: false,
      icon: MessageSquare,
    },
    {
      id: "slack",
      name: "Slack",
      description: "Business communication platform",
      command: "sudo snap install slack",
      category: "Communication",
      recommended: false,
      icon: Slack,
    },
    {
      id: "zoom",
      name: "Zoom",
      description: "Video conferencing tool",
      command: "sudo apt install zoom",
      category: "Communication",
      recommended: false,
      icon: Video,
    },
  ],
}

/**
 * Package manager setup commands for each operating system
 */
export const setupCommands: Record<OperatingSystem, string> = {
  windows:
    "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))",
  macos: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
  linux: "sudo apt update && sudo apt upgrade -y",
}

